const queries = {
    queries: [
        "<interrogative pronoun> <do verb> <demonstrative pronoun>",
        "<interrogative pronoun> <imperfect auxillary verb> <imperfect verb>",
        "<determined noun phrase> <auxillary verb> <verb phrase>",
        "<determined noun phrase> <verb>",
        "<pronoun> <auxillary verb> <verb>",
        "<plural noun phrase> <verb>",
        "<personal object pronoun> <verb>",
        "<possessive adjective pronoun> <noun>",
        "<interjection> <adjective> <noun>",
        "<adjective> <interrogative pronoun> <auxillary verb>",
        "<determined noun phrase> <conjuction> <determined noun phrase>",
        "<plural noun phrase> <conjuction> <plural noun phrase>",
        "<adjective> <adjective> <noun>",
        "<adjective> <noun> <verb>",
        "<pronoun> <verb> <interrogative pronoun>",
        "<adverb> <verb> <interrogative pronoun>",
        "<determinaned noun phrase>",
        "<interrogative pronoun> <verb> <determined noun phrase>",
        "<interrogative pronoun> <verb> <plural noun phrase>",
        "<determined noun phrase> <verb> <adverb>",
        "<adjective> <noun> <interjection>",
        "<adjective> <verb> <adjective> <noun>",
        "<pronoun> <auxillary verb> <verb> <adverb>",
        "<plural noun phrase> <verb> <adjective> <noun>",
        "<interjection> <adjective> <verb> <determined noun phrase>",
        "<adverb> <interjection> <adjective> <noun>",
        "<determined noun phrase> <conjuction> <adjective> <noun>",
        "<determined noun phrase> <verb> <adjective> <interjection>",
        "<pronoun> <auxillary verb> <verb> <adjective> <adverb>",
        "<adjective> <adjective> <adjective> <noun>",
        "<pronoun> <verb> <adjective> <noun>",
        "<pronoun> <verb> <determined noun phrase> <conjuction> <determined noun phrase>",
        "<adjective> <noun> <conjuction> <adjective> <noun>",
        "<adjective> <adjective> <verb> <adjective> <noun>",
        "<adjective> <verb> <pronoun> <auxillary verb> <verb>",
        "<interrogative pronoun> <imperfect auxillary verb> <imperfect verb> <adjective> <noun>",
        "<adverb> <adjective> <interjection> <pronoun> <auxillary verb>",
        "<interrogative pronoun> <past verb> <determined noun phrase>",
        "<interrogative pronoun> <noun phrase> <imperfect auxillary verb> <imperfect verb> <determined noun phrase>",
        "<adverb> <verb> <interrogative pronoun>",
        "<determined noun phrase> <verb> <interrogative pronoun>",
        "<interrogative pronoun> <do verb> <demonstrative pronoun>",
        "<interrogative pronoun> <imperfect auxillary verb> <imperfect verb>",
    ]
};

export default queries;