const statements = {
    statements: [
        "<interrogative pronoun> <do verb> <demonstrative pronoun>",
        "<interrogative pronoun> <imperfect auxillary verb> <imperfect verb>",
        "<determined noun phrase> <auxillary verb> <verb phrase>",
        "<determined noun phrase> <past verb>",
        "<plural noun phrase> <past verb> <determined noun phrase>",
        "<possessive adjective pronoun> <noun>",
        "<personal subject pronoun> <imperfect auxillary verb> <possessive adjective pronoun> <noun>",
        "<determined noun phrase> <conjuction> <determined noun phrase>",
        "<plural noun phrase> <conjuction> <plural noun phrase>",
        "<determinant> <adjective> <conjuction> <adjective> <noun>",
        "<adjective> <noun> <imperfect auxillary verb> <past verb>",
        "<determined noun phrase>",
        "<interrogative pronoun> <past verb> <determined noun phrase>",
        "<interrogative pronoun> <noun phrase> <imperfect auxillary verb> <imperfect verb> <determined noun phrase>",
        "<determined noun phrase> <verb> <adverb>",
        "<interjection>, <noun phrase>",
        "<noun phrase>, <interjection>",
        "<verb phrase> <determined noun phrase>",
        "<pronoun> <auxillary verb> <verb> <personal object pronoun> <adverb>",
        "<plural noun phrase> <auxillary verb> <verb phrase> <simple preposition> <determined noun phrase>|<plural noun phrase>",
        "<plural noun phrase> <auxillary verb> <adverb> <past verb> <simple preposition> <determined noun phrase>|<plural noun phrase>",
        "<interjection>, <verb phrase> <determined noun phrase>",
        "<verb phrase> <possessive adjective pronoun> <noun phrase>",
        "<verb> <possessive adjective pronoun> <noun phrase> <adverb>",
        "<verb phrase> <simple preposition> <possessive adjective pronoun> <noun phrase>",
        "<determined noun phrase> <conjuction> <determined noun phrase>",
        "<determined noun phrase> <auxillary verb> <verb phrase>, <interjection>",
        "<determined noun phrase> <auxillary verb> <verb> very <adverb>",
        "<determinant> <adjective> <adjective> <adjective> <noun>",
        "<pronoun> <verb> <preposition> <determined noun phrase> <conjuction> <preposition> <verb phrase>",
        "<pronoun> <verb> <preposition> <determined noun phrase> <conjuction> <preposition> <determined noun phrase>",
        "<determined noun phrase> <conjuction> <determined noun phrase>",
        "<determinant> <adjective> <adjective> <verb> <noun phrase>",
        "<determinant> <adjective> <verb> <pronoun> <auxillary verb> <verb>",
        "<interrogative pronoun> <imperfect auxillary verb> <imperfect verb> <determinaned noun phrase>",
    ]   
}

export default statements;