const perfectAuxillary = ["have|has|had|can|could|may|might|shall|should|will|would|must"];
const imperfectAuxillary = ["am|is|are|was|were|'will be'|'shall be'"];
const doAuxillaryVerb = ["do|does|did"];
const present = [
                "abate|abandon|abduct|abjure|abolish|abort|abscond|abuse|accept|acclaim|accord",
                "account|accumulate|accuse|achieve|acknowledge|acquire|acquit|act|adjourn|adjust",
                "administer|admire|admit|adorn|advance|advantage|advertise|advise|advocate|affirm",
                "afflict|afford|affront|age|aggregate|agree|aim|aid|align|allow|allude|alter",
                "amaze|ambush|amend|amuse|analyze|announce|answer|antagonize|anticipate|apologize",
                "appeal|appear|applaud|apply|appoint|appreciate|approach|approve|argue|arise",
                "arraign|arrest|arrive|arouse|articulate|ascend|ashame|assign|assist|astonish",
                "attach|attempt|attack|attain|attend|attract|authorize|avail|avenge|avert|avow",
                "awaken|award|backfire|back|bag|balance|banish|bank|baptize|barber|barrel|barricade",
                "barter|bathe|bat|batter|battle|bawl|beam|beard|beat|beautify|becalm|become",
                "bedevil|befit|beg|beguile|behave|behead|believe|belong|bemoan|benefit",
                "be|bend|bequeath|berate|bereave|besiege|besmirch|bestow|betray|betroth|bet|bet",
                "bewail|bewilder|bid|bid|bill|bin|biopsy|bite|blacken|blackmail|blame|blanch",
                "blend|bless|bleed|blight|blind|block|blood|blow|boast|boil|bolt|bomb|bond",
                "book|boot|bore|borrow|boss|botch|bounce|bow|brag|braid|branch|brave|breach",
                "break|broom|bruise|brush|bubble|budget|buffet|build|bully|bump|bunk|bury",
                "burn|burst|bury|bust|buzz|calculate|call|calm|camouflage|cancel|canvas|cap",
                "capture|caress|caricature|carry|carve|castigate|catalog|cater|catch|cease|celebrate",
                "censor|centrifuge|challenge|change|characterize|charge|charm|cheat|check|cheer",
                "chew|choke|choose|chop|christen|chuckle|churn|circulate|claim|clean|clear",
                "climb|clip|cloak|clog|close|clothe|clout|coach|coat|coerce|coin|collect",
                "collide|color|comb|combine|comfort|command|commemorate|communicate|commuterize",
                "compare|compel|compensate|compete|complain|complete|compliment|compose|compound",
                "compress|conceal|conceive|concentrate|conceal|conclude|condemn|conduct|confess|configure"
];
const past = [
                "abated|abandoned|abducted|abjured|abolished|aborted|absconded|abused|accepted|acclaimed|accorded",
                "accounted|accumulated|accused|achieved|acknowledged|acquired|acquitted|acted|adjourned|adjusted",
                "administered|admired|admitted|adorned|advanced|advantaged|advertised|advised|advocated|affirmed",
                "afflicted|afforded|affronted|aged|aggregated|agreed|aimed|aided|aligned|allowed|alluded|altered", 
                "amazed|ambushed|amended|amused|analyzed|announced|answered|antagonized|anticipated|apologized",
                "appealed|appeared|applauded|applied|appointed|appreciated|approached|approved|argued|arisen",
                "arraigned|arrested|arrived|aroused|articulated|ascended|ashamed|assigned|assisted|astonished",
                "attached|attempted|attacked|attained|attended|attracted|authorized|availed|avenged|averted|avowed",
                "awakened|awarded|backfired|backed|bagged|balanced|banished|banked|baptized|barbered|barreled|barricaded",
                "bartered|bathed|batted|battered|battled|bawled|beamed|bearded|beaten|beautified|becalmed|become",
                "bedeviled|befitted|begged|beguiled|behaved|beheaded|believed|belonged|bemoaned|benefited",
                "benign|bent|bequeathed|berated|bereft|besieged|besmirched|bestowed|betrayed|betrothed|betted",
                "bewailed|bewildered|bid|bidden|billed|binned|biopsied|bitten|blackened|blackmailed|blamed|blanched",
                "blended|blessed|bled|blighted|blinded|blocked|bloodied|blown|boasted|boiled|bolted|bombed|bonded",
                "booked|booted|bored|borrowed|bossed|botched|bounced|bowed|bragged|braided|branched|braved|breached",
                "broken|broomed|bruised|brushed|bubbled|budgeted|buffeted|built|bullied|bumped|bunked|buried",
                "burned|burst|buried|busted|buzzed|calculated|called|calmed|camouflaged|cancelled|canvassed|capped",
                "captured|caressed|caricatured|carried|carved|castigated|catalogued|catered|caught|ceased|celebrated",
                "censored|centrifuged|challenged|changed|characterized|charged|charmed|cheated|checked|cheered",
                "chewed|choked|chosen|chopped|christened|chuckled|churned|circulated|claimed|cleaned|cleared",
                "climbed|clipped|cloaked|clogged|closed|clothed|clouted|coached|coated|coerced|coined|collected",
                "collided|colored|combed|combined|comforted|commanded|commemorated|communicated|commuterized",
                "compared|compelled|compensated|competed|complained|completed|complimented|composed|compounded",
                "compressed|concealed|conceived|concentrated|concealed|concluded|condemned|conducted|confessed|configured"
            ]
const imperfect = [
                "abating|abandoning|abducting|abjuring|abolishing|aborting|absconding|abusing|accepting|acclaiming|according",
                "accounting|accumulating|accusing|achieving|acknowledging|acquiring|acquitting|acting|adjourning|adjusting",
                "administering|admiring|admitting|adorning|advancing|advantaging|advertising|advising|advocating|affirming",
                "afflicting|affording|affronting|aging|aggregating|agreeing|aiming|aiding|aligning|allowing|alluding|altering",
                "amazing|ambushing|amending|amusing|analyzing|announcing|answering|antagonizing|anticipating|apologizing",
                "appealing|appearing|applauding|applying|appointing|appreciating|approaching|approving|arguing|arising",
                "arraigning|arresting|arriving|arousing|articulating|ascending|ashaming|assigning|assisting|astonishing",
                "attaching|attempting|attacking|attaining|attending|attracting|authorizing|availing|avenging|averting|avowing",
                "awakening|awarding|backfiring|backing|bagging|balancing|banishing|banking|baptizing|barbering|barreling|barricading",
                "battering|battling|bawling|beaming|bearding|beating|beautifying|becalming|becoming|bedeviling|befitting",
                "begging|beguiling|behaving|beheading|believing|belonging|bemoaning|benefiting|benigning|bending|bequeathing",
                "berating|berefting|besieging|besmirching|bestowing|betraying|betrothing|bettering|bewailing|bewildering",
                "bidding|biding|billing|binning|biopsying|biting|blackening|blackmailing|blaming|blanching|blending",
                "blessing|bleeding|blighting|blinding|blocking|blooding|blowing|boasting|boiling|bolting|bombing|bonding",
                "booking|booting|boring|borrowing|bossing|botching|bouncing|bowing|bragging|braiding|branching|braving|breaking",
                "brooming|bruising|brushing|bubbling|budgeting|buffeting|building|bullying|bumping|bunking|burying",
                "burning|bursting|busting|buzzing|calculating|calling|calming|camouflaging|cancelling|canvassing|capping",
                "capturing|caressing|caricaturing|carrying|carving|castigating|cataloguing|catering|catching|ceasing|celebrating",
                "censoring|centrifuging|challenging|changing|characterizing|charging|charming|cheating|checking|cheering",
                "chewing|choking|choosing|chopping|christening|chuckling|churning|circulating|claiming|cleaning|clearing",
                "climbing|clipping|cloaking|clogging|closing|clothing|clouting|coaching|coating|coercing|coining|collecting",
                "colliding|coloring|combing|combining|comforting|commanding|commemorating|communicating|commuterizing",
                "comparing|compelling|compensating|competing|complaining|completing|complimenting|composing|compounding",
                "compressing|concealing|conceiving|concentrating|concluding|condemning|conducting|confessing|configuring"
];

const verbs = {
    do: doAuxillaryVerb,
    perfectAuxillary: perfectAuxillary,
    imperfectAuxillary: imperfectAuxillary,
    past: past,
    present: present,
    imperfect: imperfect,
}

export default verbs;